version: '3.8'

services:
  soc-assistant:
    build: .
    container_name: Soc_netcomp
    ports:
      - "8000:8000"
    environment:
      # Inject your personalized keys provided after kickoff
      #  to do with encryption
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      # Mount datasets for real-time log ingestion without rebuilding
      - ./datasets/app/datasets
    restart: always